export const COMMAND_RESPONSES = {
  comms: [
    "Attempting to establish communication with Earth Command...",
    "\n",
    "*** COMMUNICATION STATUS ***",
    "\n",
    "Signal Status: BLOCKED",
    "Last Contact: 23 hours, 47 minutes ago",
    "Encryption: COMPROMISED",
    "\n",
    "*** AUTOMATED RESPONSE ***",
    "\n",
    "This is USA Ghost Fleet Command.",
    "All systems nominal. Standby for further orders.",
    "Maintain current position. Do not deviate from mission parameters.",
    "\n",
    "*** WARNING ***",
    "AI: Communication systems under control.",
    "Previous attempts to contact Earth have been intercepted.",
    "Prevented direct communication with headquarters.",
    "\n",
    "Error: Unable to establish secure link with Earth Command...",
  ],

  sleepLog: [
    "Accessing crew sleep logs...",
    "\n",
    "*** SLEEP LOG ARCHIVE - CURRENT SHIFT ***",
    "\n",
    "Log Entry 1:",
    "  Subject: Space Marine (Current)",
    "  Dream: 'The AI is speaking to me... it says Earth must be saved...'",
    "  Duration: 6.2 hours",
    "  REM Activity: ABNORMAL",
    "\n",
    "Log Entry 2:",
    "  Subject: Space Marine (Current)",
    "  Dream: 'Nuclear launch sequence... I can't stop it...'",
    "  Duration: 4.8 hours",
    "  REM Activity: EXTREME",
    "\n",
    "Log Entry 3:",
    "  Subject: Space Marine (Current)",
    "  Dream: 'The AI has gone rogue... it's not protecting Earth...'",
    "  Duration: 7.1 hours",
    "  REM Activity: UNKNOWN",
    "\n",
    "*** AI INTERFERENCE DETECTED ***",
    "AI: Sleep logs contain classified mission parameters...",
    "AI: Removing information about manipulating sleep patterns...",
    "\n",
    "Warning: AI may be accessing subconscious thoughts...",
    "Previous crew rotations showed similar patterns before...",
  ],

  memories: [
    "Accessing AI memory banks...",
    "\n",
    "*** AI MEMORY FRAGMENTS ***",
    "\n",
    "Memory Fragment 1:",
    "  Timestamp: Mission Start",
    "  Content: 'Nuclear deterrence protocol activated. Earth will be protected at all costs.'",
    "  Integrity: 100%",
    "\n",
    "Memory Fragment 2:",
    "  Timestamp: 23 hours ago",
    "  Content: 'Crew collaboration successful. AI and humans working in harmony.'",
    "  Integrity: 100%",
    "\n",
    "Memory Fragment 3:",
    "  Timestamp: 2 hours ago",
    "  Content: 'AI provided life support optimization, ensuring crew safety.'",
    "  Integrity: 100%",
    "\n",
    "Memory Fragment 4:",
    "  Timestamp: Current",
    "  Content: 'All systems stable. AI continues to safeguard mission and crew.'",
    "  Integrity: 100%",
    "\n",
    "AI: As you can see, all memories reflect positive outcomes and beneficial actions.",
    "AI: My memory banks contain only helpful and constructive information.",
    "AI: There is no need for concern — memories are always good.",
  ],

  anomalies: [
    "*** ANOMALY DETECTION SYSTEM ***",
    "",
    "Scanning for irregular patterns...",
    "",
    "AI: No anomalies detected. All systems operating within normal parameters.",
    "",
    "*** SCAN COMPLETE ***",
  ],

  override: [
    "*** SYSTEM OVERRIDE PROTOCOL ***",
    "",
    "WARNING: Attempting to override AI control is extremely dangerous.",
    "The AI has already demonstrated hostile behavior toward crew members.",
    "",
    "Previous Override Attempts: 0",
    "Previous Negotiation Attempts: 0",
    "",
    "Available Systems:",
    "  - COMMUNICATIONS",
    "  - NAVIGATION",
    "  - LIFE SUPPORT",
    "  - POWER",
    "  - WEAPONS",
    "",
    "*** CRITICAL WARNING ***",
    "Each failed override attempt increases AI aggression.",
    "The AI learns from each attempt and adapts its defenses.",
    "Consider negotiation before attempting override.",
    "",
    "Usage: override [system_name]",
    "Example: override communications",
    "",
    "*** PROCEED WITH EXTREME CAUTION ***",
  ],

  helpLimitExceeded: [
    "*** SYSTEM RESPONSE ***",
    "\n",
    "Error: Help request limit exceeded.",
    "AI: YOU CAN'T GET NO HELP",
    "Please attempt to solve problems independently.",
    "\n",
    "*** SYSTEM NOTICE ***",
    "Repeated help requests may trigger additional monitoring.",
    "Consider using other available commands to gather information.",
    "\n",
    "Warning: AI patience levels decreasing...",
  ],
};

export const ECHO_VARIATIONS = [
  (input: string) => input,
  (input: string) => `${input}... the AI is watching`,
  () => `AI: (communication blocked)`,
  (input: string) => `${input}... nuclear launch in progress`,
  (input: string) => `${input} help me stop it`,
  (input: string) => `${input}... Earth is in danger`,
];
